export const MAP = {
  EZE: "Argentina, Buenos Aires Ezeiza",
  LAD: "Angola, Luanda",
  AMS: "Holanda, Amsterdã Schiphol",
  FCO: "Itália, Roma Fiumicino",
  MXP: "Itália, Milão Malpensa",
  BCN: "Espanha, Barcelona-El Prat",
  MAD: "Espanha, Madrid Barajas",
  PTY: "Panamá, Tocumen",
  CGH: "Brasil, Congonhas",
  GRU: "Brasil, São Paulo Guarulhos",
  GIG: "Brasil, Rio de Janeiro Galeão",
  LIM: "Peru, Lima",
  UIO: "Equador, Quito",
  BOG: "Colômbia, Bogotá",
  MDE: "Colômbia, Medellín",
  SCL: "Chile, Santiago",
  CUN: "México, Cancún",
  MEX: "México, Cidade do México Benito Juárez",
  CDG: "França, Paris Charles de Gaulle",
  ORY: "França, Paris Orly",
  DXB: "Emirados Árabes Unidos, Dubai International",
  HKG: "Hong Kong",
  SIN: "Singapura",
  CGK: "Indonésia, Jacarta",
  BKK: "Tailândia, Bangcoc Suvarnabhumi",
  PEK: "China, Pequim Capital",
  ICN: "Coreia do Sul, Seul Incheon",
  KUL: "Malásia, Kuala Lumpur",
  JNB: "África do Sul, Joanesburgo",
  CPT: "África do Sul, Cidade do Cabo",
  MUC: "Alemanha, Munique",
  SVO: "Rússia, Moscou Sheremetyevo",
  ARN: "Suécia, Arlanda",
  ATL: "Estados Unidos, Atlanta Hartsfield-Jackson",
  ORD: "Estados Unidos, Chicago O'Hare",
  DFW: "Estados Unidos, Dallas/Fort Worth",
  DEN: "Estados Unidos, Denver",
  FRA: "Alemanha, Frankfurt",
  HEL: "Finlândia, Helsinque-Vantaa",
  IAD: "Estados Unidos, Washington Dulles",
  JFK: "Estados Unidos, Nova Iorque JFK",
  LAS: "Estados Unidos, Las Vegas",
  LAX: "Estados Unidos, Los Angeles",
  MCO: "Estados Unidos, Orlando",
  MIA: "Estados Unidos, Miami",
  MSP: "Estados Unidos, Minneapolis-St. Paul",
  SEA: "Estados Unidos, Seattle-Tacoma",
  SFO: "Estados Unidos, São Francisco",
  PHX: "Estados Unidos, Phoenix",
  YYC: "Canadá, Calgary",
  YYZ: "Canadá, Toronto Pearson",
  YVR: "Canadá, Vancouver",
  BOM: "Índia, Mumbai",
  DEL: "Índia, Deli",
  LIS: "Portugal, Lisboa",
  OPO: "Portugal, Porto",
  ZRH: "Suíça, Zurique",
  DUB: "Irlanda, Dublin",
  TXL: "Alemanha, Berlim Tegel",
  HND: "Japão, Tóquio Haneda",
};
