export const MAP = {
  EZE: "Argentina, Buenos Aires Ezeiza",
  LAD: "Angola, Luanda",
  AMS: "Netherlands, Amsterdam Schiphol",
  FCO: "Italy, Rome Fiumicino",
  MXP: "Italy, Milan Malpensa",
  BCN: "Spain, Barcelona-El Prat",
  MAD: "Spain, Madrid Barajas",
  PTY: "Panama, Tocumen",
  CGH: "Brazil, Congonhas",
  GRU: "Brazil, São Paulo Guarulhos",
  GIG: "Brazil, Rio de Janeiro Galeão",
  LIM: "Peru, Lima",
  UIO: "Ecuador, Quito",
  BOG: "Colombia, Bogotá",
  MDE: "Colombia, Medellín",
  SCL: "Chile, Santiago",
  CUN: "Mexico, Cancun",
  MEX: "Mexico, Mexico City Benito Juárez",
  CDG: "France, Paris Charles de Gaulle",
  ORY: "France, Paris Orly",
  DXB: "United Arab Emirates, Dubai International",
  HKG: "Hong Kong",
  SIN: "Singapore",
  CGK: "Indonesia, Jakarta",
  BKK: "Thailand, Bangkok Suvarnabhumi",
  PEK: "China, Beijing Capital",
  ICN: "South Korea, Seoul Incheon",
  KUL: "Malaysia, Kuala Lumpur",
  JNB: "South Africa, Johannesburg",
  CPT: "South Africa, Cape Town",
  MUC: "Germany, Munich",
  SVO: "Russia, Moscow Sheremetyevo",
  ARN: "Sweden, Arlanda",
  ATL: "United States, Atlanta Hartsfield-Jackson",
  ORD: "United States, Chicago O'Hare",
  DFW: "United States, Dallas/Fort Worth",
  DEN: "United States, Denver",
  FRA: "Germany, Frankfurt",
  HEL: "Finland, Helsinki-Vantaa",
  IAD: "United States, Washington Dulles",
  JFK: "United States, New York JFK",
  LAS: "United States, Las Vegas",
  LAX: "United States, Los Angeles",
  MCO: "United States, Orlando",
  MIA: "United States, Miami",
  MSP: "United States, Minneapolis-St. Paul",
  SEA: "United States, Seattle-Tacoma",
  SFO: "United States, San Francisco",
  PHX: "United States, Phoenix",
  YYC: "Canada, Calgary",
  YYZ: "Canada, Toronto Pearson",
  YVR: "Canada, Vancouver",
  BOM: "India, Mumbai",
  DEL: "India, Delhi",
  LIS: "Portugal, Lisbon",
  OPO: "Portugal, Porto",
  ZRH: "Switzerland, Zurich",
  DUB: "Ireland, Dublin",
  TXL: "Germany, Berlin Tegel",
  HND: "Japan, Tokyo Haneda",
};
